- name: Install etcd
  apt:
    name: etcd
    state: present
  notify:
    - restart etcd

- name: Create etcd config
  template:
      src: "../templates/etcd.j2"
      dest: "/etc/default/etcd"
      owner: "root"
      group: "root"
      mode:  0644
  become: true
  notify: restart etcd
